---
- name: Setup nginx and firewall settings on a Debian 10 host

  # Specify the hosts you want to target
  hosts: all

  vars:
    system_packages: ["nginx"]

  tasks:
    - name: Update apt
      become: yes
      become_user: root
      apt: update_cache=yes

    - name: Install required system packages
      become: yes
      become_user: root
      apt: name={{ system_packages }} state=latest

    - name: Enable nginx to start on boot
      become: yes
      become_user: root
      systemd:
        name: nginx
        enabled: yes

    - name: Start nginx server
      become: yes
      become_user: root
      systemd:
        name: nginx
        state: started
