---
- name: Setup dwata with Git

  # Specify the hosts you want to target
  hosts: all

  vars:
    projects_root: /home/vagrant
    project_repo_url: https://github.com/brainless/dwata.git
    python_path: /usr/bin/python3
    project_name: "dwata"

  tasks:
    - name: Clone project repo
      git:
        repo: "{{ project_repo_url }}"
        accept_hostkey: yes
        dest: "{{ projects_root }}/{{ project_name }}"
        version: develop

    - name: Install/update Python requirements for backend
      pip:
        requirements: "{{ projects_root }}/{{ project_name }}/backend/requirements.txt"
        chdir: "{{ projects_root }}/{{ project_name }}/backend"
        virtualenv_python: "/usr/bin/python3"
        virtualenv: "{{ projects_root }}/{{ project_name }}/backend/.venv"

    - name: Copy nginx config files
      copy:
        src: "{{ item }}"
        dest: "/etc/nginx/sites-available/"
        remote_src: yes
      with_items:
        - "{{ projects_root }}/{{ project_name }}/system/nginx/{{ project_name }}_local.conf"
      become: yes
      become_user: "root"

    - name: Symlink nginx config files to sites-enabled
      file:
        src: "/etc/nginx/sites-available/{{ item }}"
        dest: "/etc/nginx/sites-enabled/{{ item }}"
        state: link
      with_items:
        - "{{ project_name }}_local.conf"
      become: yes
      become_user: "root"
