---
- name: Setup python, nginx, git and other software on a Debian 10+ host

  # Specify the hosts you want to target
  hosts: all

  vars:
    system_packages:
      [
        "nginx",
        "redis-server",
        "git",
        "rsync",
        "python3-pip",
        "python3-virtualenv",
        "build-essential",
        "virtualenv",
        "libssl-dev",
        "zlib1g-dev",
        "libncurses5-dev",
        "libnss3-dev",
        "libncursesw5-dev",
        "libreadline-dev",
        "libsqlite3-dev",
        "libgdbm-dev",
        "libdb5.3-dev",
        "libbz2-dev",
        "libexpat1-dev",
        "liblzma-dev",
        "libffi-dev",
        "libpq-dev",
      ]

  tasks:
    - name: Update apt
      become: yes
      become_user: root
      apt: update_cache=yes

    - name: Install required system packages
      become: yes
      become_user: root
      apt: name={{ system_packages }} state=latest

    - name: Enable nginx to start on boot
      become: yes
      become_user: root
      systemd:
        name: nginx
        enabled: yes

    - name: Start nginx server
      become: yes
      become_user: root
      systemd:
        name: nginx
        state: started
