---
- name: Setup nginx and uvicorn services in systemd

  # Specify the hosts you want to target
  hosts: all

  tasks:
    - name: Enable nginx to start on boot
      systemd:
        name: nginx
        enabled: yes
      become: yes
      become_user: root

    - name: Start nginx server
      systemd:
        name: nginx
        state: started
      become: yes
      become_user: root

    - name: Enable uvicorn to start on boot
      systemd:
        name: uvicorn
        enabled: yes
      become: yes
      become_user: root

    - name: Start uvicorn server
      systemd:
        name: uvicorn
        state: started
      become: yes
      become_user: root
